CREATE DATABASE QuanLyTapHoa_Nhom1;
GO
USE QuanLyTapHoa_Nhom1;
GO

CREATE TABLE Tinh (
    MaTinh SMALLINT PRIMARY KEY,
	TenTinh NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE Xa (
    MaXa INT PRIMARY KEY,
	TenXa NVARCHAR(50) NOT NULL,
	MaTinh SMALLINT NOT NULL,
	CONSTRAINT FK_Xa_Tinh FOREIGN KEY (MaTinh)
        REFERENCES Tinh(MaTinh) ON DELETE CASCADE
);
GO

CREATE TABLE NhaCC (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    DienThoaiNCC VARCHAR(15) NOT NULL,
    EmailNCC VARCHAR(100),
    DiaChiNCC NVARCHAR(255) NOT NULL,
	MaXa INT NOT NULL,
	CONSTRAINT FK_Xa_NhaCC FOREIGN KEY (MaXa)
        REFERENCES Xa(MaXa)
);
GO

CREATE TABLE KhachHang(
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    AnhKH NVARCHAR(255),
    GioiTinh BIT,
    EmailKH NVARCHAR(255),
    DienThoaiKH VARCHAR(10) NOT NULL,
    DiaChiKH NVARCHAR(255),
	MaXa INT,
	CONSTRAINT FK_Xa_KhachHang FOREIGN KEY (MaXa)
        REFERENCES Xa(MaXa)
);
GO

CREATE TABLE TaiKhoan(
	MaTK CHAR(5) PRIMARY KEY,
	TenDN VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(20) NOT NULL,
	VaiTro BIT NOT NULL
);
GO

CREATE TABLE NhomSP (
    MaNhom VARCHAR(10) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE LoaiSP(
    MaLoai VARCHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL,
    MaNhom VARCHAR(10) NOT NULL,
    CONSTRAINT FK_LoaiSP_NhomSP FOREIGN KEY (MaNhom)
        REFERENCES NhomSP(MaNhom)
);
GO

CREATE TABLE TrangThai(
	MaTT CHAR(3) PRIMARY KEY,
	TenTT NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE SanPham(
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(50) NOT NULL,
    GiaBan DECIMAL(18,2) NOT NULL,
	MaTT CHAR(3) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    CONSTRAINT FK_SanPham_LoaiSP FOREIGN KEY (MaLoai)
        REFERENCES LoaiSP(MaLoai),
	CONSTRAINT FK_SanPham_TrangThai FOREIGN KEY (MaTT)
        REFERENCES TrangThai(MaTT)
);
GO

CREATE TABLE DonMuaHang(
    MaDMH CHAR(11) PRIMARY KEY,
    NgayMH DATE NOT NULL,
    MaNCC VARCHAR(10) NOT NULL
    CONSTRAINT FK_DonMuaHang_NhaCC FOREIGN KEY (MaNCC)
        REFERENCES NhaCC(MaNCC)
);
GO

CREATE TABLE DonBanHang(
    MaDBH CHAR(11) PRIMARY KEY,
    NgayBH DATE NOT NULL,
    MaKH VARCHAR(10) NOT NULL,
    CONSTRAINT FK_DonBanHang_KhachHang FOREIGN KEY (MaKH)
        REFERENCES KhachHang(MaKH)
);
GO

CREATE TABLE CTMH(
    MaDMH CHAR(11) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SLM INT NOT NULL,
    DGM DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CTMH PRIMARY KEY(MaDMH, MaSP),
    CONSTRAINT FK_CTMH_DonMuaHang FOREIGN KEY (MaDMH)
        REFERENCES DonMuaHang(MaDMH) ON DELETE CASCADE,
    CONSTRAINT FK_CTMH_SanPham FOREIGN KEY (MaSP)
        REFERENCES SanPham(MaSP)
);
GO

CREATE TABLE CTBH(
    MaDBH CHAR(11) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SLB INT NOT NULL,
    DGB DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CTBH PRIMARY KEY(MaDBH, MaSP),
    CONSTRAINT FK_CTBH_DonBanHang FOREIGN KEY (MaDBH)
        REFERENCES DonBanHang(MaDBH) ON DELETE CASCADE,
    CONSTRAINT FK_CTBH_SanPham FOREIGN KEY (MaSP)
        REFERENCES SanPham(MaSP)
);
GO
