CREATE DATABASE QuanLyTapHoa_Nhom1;
GO
USE QuanLyTapHoa_Nhom1;
GO

CREATE TABLE Tinh (
    MaTinh SMALLINT NOT NULL PRIMARY KEY,
    TenTinh NVARCHAR(50) NOT NULL,
);
CREATE TABLE Xa (
    MaXa SMALLINT NOT NULL PRIMARY KEY,
    MaTinh SMALLINT,
    TenXa NVARCHAR(50),
    CONSTRAINT FK_Xa_Tinh FOREIGN KEY (MaTinh) REFERENCES Tinh(MaTinh)
);
CREATE TABLE KhachHang (
    MaKH CHAR(10) NOT NULL PRIMARY KEY,
    MaXa SMALLINT,
    TenKH NVARCHAR(50),
    SDT CHAR(10),
    Email VARCHAR(100),
    DiaChi NVARCHAR(255),
    CONSTRAINT FK_KhachHang_Xa FOREIGN KEY (MaXa) REFERENCES Xa(MaXa)
);
CREATE TABLE NhaCungCap (
    MaNCC CHAR(10) NOT NULL PRIMARY KEY,
    MaXa SMALLINT,
    TenNCC NVARCHAR(100),
    DiaChi NVARCHAR(200),
    SDT CHAR(10),
    Email VARCHAR(100),
    CONSTRAINT FK_NCC_Xa FOREIGN KEY (MaXa) REFERENCES Xa(MaXa)
);
CREATE TABLE LoaiSanPham (
    MaLoai CHAR(10) NOT NULL PRIMARY KEY,
    TenLoai NVARCHAR(50)
);
CREATE TABLE SanPham (
    MaSP CHAR(10) NOT NULL PRIMARY KEY,
    MaLoai CHAR(10),
    TenSP NVARCHAR(100),
    GiaBan DECIMAL(18,2),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_SP_LoaiSP FOREIGN KEY (MaLoai) REFERENCES LoaiSanPham(MaLoai)
);
CREATE TABLE DonBanHang (
    MaDBH CHAR(10) NOT NULL PRIMARY KEY,
    MaKH CHAR(10),
    NgayBH DATETIME,
    CONSTRAINT FK_DonBan_KH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);
CREATE TABLE ChiTietBanHang (
    MaDBH CHAR(10) NOT NULL,
    MaSP CHAR(10) NOT NULL,
    SoLuongBan INT,
    DonGiaBan DECIMAL(18,2),
    PRIMARY KEY (MaDBH, MaSP),
    CONSTRAINT FK_CTBH_DonBan FOREIGN KEY (MaDBH) REFERENCES DonBanHang(MaDBH),
    CONSTRAINT FK_CTBH_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
CREATE TABLE DonMuaHang (
    MaDMH CHAR(20) NOT NULL PRIMARY KEY,
    MaNCC CHAR(10),
    NgayMH DATETIME,
    CONSTRAINT FK_DonMua_NCC FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);
CREATE TABLE ChiTietMuaHang (
    MaDMH CHAR(20) NOT NULL,
    MaSP CHAR(10) NOT NULL,
    SoLuongMua INT,
    DonGiaMua DECIMAL(18,2),
    PRIMARY KEY (MaDMH, MaSP),
    CONSTRAINT FK_CTMH_DonMua FOREIGN KEY (MaDMH) REFERENCES DonMuaHang(MaDMH),
    CONSTRAINT FK_CTMH_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
